### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "john@gmail.com",
    "password": "secret"
}

### Sign in a user
POST http://localhost:3000/auth/signin
Content-Type: application/json

# Cookie Session will not send any cookie headers if there are no changes to session object
{
    "email": "harsh@gmail.com",
    "password": "secret"
}

### Sign out a user
GET http://localhost:3000/auth/signout

### Show current user
GET http://localhost:3000/auth/showCurrentUser


### Find a particular user
GET http://localhost:3000/auth/1


### Find all users
GET http://localhost:3000/auth?email=akshad@gmail.com



### Update a particular user
PATCH http://localhost:3000/auth/30
Content-Type: application/json

{
    "password": "secret"
}


### Remove a particular user
DELETE http://localhost:3000/auth/2
